language: php

php:
  - '7.1'
  - '7.2'

before_script:
  - touch database/database-testing.sqlite
  - cp .env.example .env
  - composer install
  - composer dumpautoload -o
  - php artisan optimize
  - php artisan migrate --seed
